/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: "category",
      label: "GitLab",
      link: {
        type: "generated-index",
        title: "GitLab",
        description: "Articles related to GitLab",
      },
      items: [
        {
          type: "category",
          label: "Administrator Guide",
          link: {
            type: "generated-index",
            title: "Administrator Guide",
            description: "Administrator Guide for GitLab Helm Chart",
          },
          items: [
            "gitlab/install-gitlab-with-helm",
            "gitlab/enable-git-over-ssh-for-gitlab",
            "gitlab/enable-ad-login-for-gitlab",
            "gitlab/gitlab-properly-signed-tls",
            "gitlab/enable-gitlab-managed-terraform-backend",
            "gitlab/provide-custom-ca-gitlab-ci-jobs",
            "gitlab/cron-backup-gitlab-ee-16.x",
            "gitlab/gitlab-runner-https-certificate-error",
          ],
        },
        {
          type: "category",
          label: "Developer Guide",
          link: {
            type: "generated-index",
            title: "Developer Guide",
            description: "Developer Guide for GitLab",
          },
          items: [
            "gitlab/use-gitlab-managed-terraform-backend",
            "gitlab/setting-up-gitlab-cli",
            "gitlab/setting-up-vscode-for-gitlab",
            "gitlab/use-custom-ca-gitlab-ci-jobs",
            "gitlab/add-project-group-runner",
            "gitlab/configure-a-git-pre-commit-hook",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Cloud",
      link: {
        type: "generated-index",
        title: "Cloud",
        description: "Articles related to cloud",
      },
      items: [
        {
          type: "category",
          label: "AWS",
          link: {
            type: "generated-index",
            title: "AWS",
            description: "Articles related to AWS",
          },
          items: [
            "aws/setting-up-cost-alerts",
            "aws/use-athena-to-query-vpc-flow-log",
            "aws/destroy-ec2-after-24h",
            "aws/install-cloudwatch-agent-on-ec2",
            "aws/nat-gateway-cannot-reach-internet",
            "aws/migrate-ec2-encrypted-ebs-default-kms",
            "aws/cross-region-vpc-peering",
            "cloud/aws-azure-s2s-vpn",
            "aws/al2023-403-forbidden-when-fetching-repository-metadata",
            "aws/aws-mgmt-switch-role",
            "aws/amazon-ses-recipient-unverified",
            "aws/cloudwatch-logs-insights-vpc-flow-logs",
            "aws/eksctl-create-cluster",
            "aws/aws-load-balancer-controller-helm",
            "aws/amazon-eks-ingress-nginx",
            "aws/amazon-eks-addon-snapshot-controller",
            "aws/amazon-eks-addon-aws-ebs-csi-driver",
          ],
        },
        {
          type: "category",
          label: "Azure",
          link: {
            type: "generated-index",
            title: "Azure",
            description: "Articles related to Microsoft Azure",
          },
          items: [
            "azure/cross-region-vnet-peering",
            "cloud/aws-azure-s2s-vpn",
            "azure/virtual-desktop-faq",
            "azure/cloud-sync-ad-ds-entra-id",
            "azure/virtual-desktop-prepare-golden-image-manual",
            "azure/fslogix-avd-ad-ds",
          ],
        },
        {
          type: "category",
          label: "Alibaba Cloud",
          link: {
            type: "generated-index",
            title: "Alibaba Cloud",
            description: "Articles related to Alibaba Cloud",
          },
          items: [
            "aliyun/setting-up-budget-alerts",
            "aliyun/set-up-dns-privatezone",
            "aliyun/ecs-lifecycle-function",
            "aliyun/set-up-direct-mail",
            "aliyun/faq",
            "aliyun/billing-items",
            "aliyun/centos-7-could-not-resolve-host",
          ],
        },
        {
          type: "category",
          label: "Citrix Cloud",
          link: {
            type: "generated-index",
            title: "Citrix Cloud",
            description: "Articles related to Citrix Cloud",
          },
          items: ["citrix/cloud-migration", "citrix/statement-of-work"],
        },
        {
          type: "category",
          label: "CommVault",
          link: {
            type: "generated-index",
            title: "CommVault",
            description: "Articles related to CommVault",
          },
          items: ["commvault/aws-ebs-direct-apis"],
        },
      ],
    },
    {
      type: "category",
      label: "Kubernetes",
      link: {
        type: "generated-index",
        title: "Kubernetes",
        description: "Articles related to Kubernetes",
      },
      items: [
        {
          type: "category",
          label: "K3s",
          link: {
            type: "generated-index",
            title: "K3s",
            description: "Articles related to K3s",
          },
          items: [
            "kubernetes/k3s-bootstrap-and-preparation",
            "kubernetes/k3s-local-path-marked-default-on-reboot",
          ],
        },
        {
          type: "category",
          label: "Rancher RKE2",
          link: {
            type: "generated-index",
            title: "Rancher RKE2",
            description: "Articles related to Rancher RKE2",
          },
          items: [
            "kubernetes/setup-rke2-for-rancher-coreos",
            "kubernetes/rke2-ha-cis-hardening",
            "kubernetes/rke2-cis-privileged-namespace",
            "kubernetes/export-kubeconfig",
            "kubernetes/running-workloads-on-a-hardened-rke2-cluster",
            "kubernetes/performing-node-maintenance-on-an-ha-cluster",
            "kubernetes/free-up-disk-space-for-rke2-nodes",
            "kubernetes/decommission-master-node-etcd-ha-cluster",
            "kubernetes/upgrade-k8s-on-rancher-rke2",
          ],
        },
        {
          type: "category",
          label: "Talos Linux",
          link: {
            type: "generated-index",
            title: "Talos Linux",
            description: "Articles related to Talos Linux",
          },
          items: [
            "kubernetes/talos-cilium-vip-3m2w",
            "kubernetes/talos-upgrade-k8s",
          ],
        },
        {
          type: "category",
          label: "Identity and access management",
          link: {
            type: "generated-index",
            title: "Identity and access management",
            description:
              "Articles related to identity and access management for Kubernetes",
          },
          items: [
            "kubernetes/kubectl-auth-whoami",
            "kubernetes/dex-oidc-ldap-backend",
            "kubernetes/kubectl-oidc-login",
            "kubernetes/keycloak-oauth2-proxy-ingress-nginx",
          ],
        },
        {
          type: "category",
          label: "Storage",
          link: {
            type: "generated-index",
            title: "Storage",
            description: "Articles related to storage on Kubernetes",
          },
          items: [
            "kubernetes/nfs-subdir-external-provisioner",
            "kubernetes/csi-driver-nfs",
            "kubernetes/rook-ceph",
            "kubernetes/longhorn-k3s",
            "kubernetes/topolvm-k3s",
          ],
        },
        {
          type: "category",
          label: "Helm",
          link: {
            type: "generated-index",
            title: "Helm",
            description: "Articles related to Helm",
          },
          items: [
            "kubernetes/safely-upgrade-a-helm-application-with-existing-settings",
            "kubernetes/roll-back-a-helm-application-to-a-specified-revision",
            "kubernetes/helm-completion-bash",
          ],
        },
        {
          type: "category",
          label: "Middleware",
          link: {
            type: "generated-index",
            title: "Middleware",
            description: "Articles related to middleware",
          },
          items: [
            "kubernetes/install-minio-on-kubernetes",
            "kubernetes/install-and-test-scylladb-for-dynamodb",
            "kubernetes/manage-on-prem-dynamodb-with-gui",
            "kubernetes/install-rabbitmq-on-kubernetes",
            "kubernetes/install-falco",
            "kubernetes/sigstore-policy-controller-custom-https-registry",
            //"kubernetes/redmine-k8s",
          ],
        },
        {
          type: "category",
          label: "Observability",
          link: {
            type: "generated-index",
            title: "Observability",
            description:
              "Articles related to observability with Prometheus and Grafana",
          },
          items: [
            "kubernetes/prometheus-grafana-node-level-metrics",
            "kubernetes/configure-prometheus-alerts-with-amazon-sns",
            "kubernetes/monitor-gitea-with-prometheus",
            "kubernetes/reset-grafana-admin-password",
            "kubernetes/enable-ad-login-for-grafana",
            "kubernetes/import-grafana-community-dashboard",
            "kubernetes/install-fluentd-fluent-bit",
            "kubernetes/forward-fluent-bit-logs-to-elasticsearch",
            "kubernetes/install-vector-agent",
            "kubernetes/forward-vector-agent-logs-to-elasticsearch",
            "kubernetes/grafana-alerting",
          ],
        },
        {
          type: "category",
          label: "Service Mesh",
          link: {
            type: "generated-index",
            title: "Service Mesh",
            description: "Articles related to Istio (and Linkerd) service mesh",
          },
          items: ["kubernetes/install-istio-with-helm"],
        },
        {
          type: "category",
          label: "FinOps",
          link: {
            type: "generated-index",
            title: "FinOps",
            description: "Articles related to FinOps",
          },
          items: ["kubernetes/install-opencost"],
        },
        {
          type: "category",
          label: "Microservices",
          link: {
            type: "generated-index",
            title: "Microservices",
            description: "Articles related to microservices",
          },
          items: [
            "kubernetes/pull-an-image-from-a-private-registry",
            "kubernetes/removing-image-vulnerabilities-from-python-microservices",
          ],
        },
        {
          type: "category",
          label: "Flux",
          link: {
            type: "generated-index",
            title: "Flux",
            description: "Articles related to Flux",
          },
          items: [
            "kubernetes/bootstrap-flux-with-git",
            "kubernetes/managing-helm-releases-declaratively-with-flux",
            "kubernetes/configuring-flux-alerts-for-helm",
            "kubernetes/drift-detection-and-correction-helm",
            "kubernetes/define-a-private-git-repository-source",
            "kubernetes/flux-completion-bash",
            "kubernetes/install-capacitor-ui-for-flux",
            "kubernetes/removing-custom-values-from-a-helmrelease",
          ],
        },
        {
          type: "category",
          label: "Argo CD",
          link: {
            type: "generated-index",
            title: "Argo CD",
            description: "Articles related to Argo CD",
          },
          items: [
            "kubernetes/install-argocd-helm",
            "kubernetes/install-argocd-cli",
            "kubernetes/argocd-completion-bash",
            "kubernetes/argocd-cli-cheatsheet",
          ],
        },
        {
          type: "category",
          label: "Cilium",
          link: {
            type: "generated-index",
            title: "Cilium",
            description: "Articles related to Cilium CNI",
          },
          items: [
            "kubernetes/talos-cilium-vip-3m2w",
            "kubernetes/cilium-lb-ipam",
            "kubernetes/cilium-egw-vip",
          ],
        },
        {
          type: "category",
          label: "Kyverno",
          link: {
            type: "generated-index",
            title: "Kyverno",
            description: "Articles related to Kyverno",
          },
          items: ["kubernetes/kyverno-installation-and-basic-usage"],
        },
        {
          type: "category",
          label: "Miscellaneous",
          link: {
            type: "generated-index",
            title: "Miscellaneous",
            description: "Articles on miscellaneous topics",
          },
          items: [
            "kubernetes/setup-jenkins-on-rancher",
            "kubernetes/configure-jenkins-to-detect-changes-on-github",
            "kubernetes/set-up-devsecops-pipeline-with-gitea-actions",
            "kubernetes/testing-an-https-clusterip-service",
            "kubernetes/gateway-404-errors-httproutes",
            "kubernetes/job-fails-container-exit-code-0",
            "kubernetes/https-registry-nginx-ingress-413-error",
            "kubernetes/testing-a-cronjob-manually",
            "kubernetes/install-krew",
            "kubernetes/kubectl-completion-bash",
            "kubernetes/kubectl-debug-node",
            "kubernetes/killer-shell-cks",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "OpenShift",
      link: {
        type: "generated-index",
        title: "OpenShift",
        description: "Articles related to OpenShift",
      },
      items: [
        {
          type: "category",
          label: "Operator Framework",
          link: {
            type: "generated-index",
            title: "Operator Framework",
            description: "Articles related to Operator Framework",
          },
          items: [
            "openshift/install-operator-sdk-olm",
            "openshift/installing-olm-operators",
          ],
        },
        {
          type: "category",
          label: "Cluster installation and setup",
          link: {
            type: "generated-index",
            title: "Cluster installation and setup",
            description: "Artiles related to cluster installation and setup",
          },
          items: [
            "openshift/install-okd-snc-upi",
            "openshift/install-ocp-snc-upi",
            "openshift/enable-image-registry-upi",
            "openshift/add-private-ca-bundle-system-trust",
          ],
        },
        {
          type: "category",
          label: "Cluster operations and maintenance",
          link: {
            type: "generated-index",
            title: "Cluster operations and maintenance",
            description:
              "Articles related to cluster operations and maintenance",
          },
          items: [
            "openshift/upgrade-ocp-via-the-web-console",
            "openshift/upgrade-ocp-via-the-command-line",
          ],
        },
        {
          type: "category",
          label: "Identity and access management",
          link: {
            type: "generated-index",
            title: "Identity and access management",
            description:
              "Articles related to identity and access management for OpenShift",
          },
          items: [
            "openshift/configure-oauth-identity-provider",
            "openshift/grant-cluster-admin-rights-to-group",
            "openshift/delete-the-kubeadmin-user",
            "openshift/install-the-keycloak-operator",
            "openshift/deploy-rhbk-ocp",
          ],
        },
        {
          type: "category",
          label: "Storage",
          link: {
            type: "generated-index",
            title: "Storage",
            description: "Articles related to storage on OpenShift",
          },
          items: [
            "openshift/install-kubevirt-hostpath-provisioner",
            "openshift/install-rook-ceph-on-sno",
            "openshift/deploy-storage-system-with-odf",
            "openshift/deploy-lvm-storage-on-sno",
          ],
        },
        {
          type: "category",
          label: "OpenShift GitOps",
          link: {
            type: "generated-index",
            title: "OpenShift GitOps",
            description: "Articles related to OpenShift GitOps",
          },
          items: ["openshift/install-openshift-gitops"],
        },
        {
          type: "category",
          label: "Middleware",
          link: {
            type: "generated-index",
            title: "Middleware",
            description: "Articles related to middleware",
          },
          items: ["openshift/deploy-minio-using-the-operator"],
        },
        {
          type: "category",
          label: "Tekton",
          link: {
            type: "generated-index",
            title: "Tekton",
            description: "Articles related to Tekton",
          },
          items: [
            "openshift/install-tekton-using-the-operator",
            "openshift/install-tkn",
            "openshift/tkn-completion-bash",
            "openshift/tkn-cli-cheatsheet",
          ],
        },
        {
          type: "category",
          label: "OpenShift Pipelines",
          link: {
            type: "generated-index",
            title: "OpenShift Pipelines",
            description: "Articles related to OpenShift Pipelines",
          },
          items: ["openshift/install-openshift-pipelines"],
        },
        {
          type: "category",
          label: "Observability",
          link: {
            type: "generated-index",
            title: "Observability",
            description: "Articles related to observability on OpenShift 4.x",
          },
          items: [
            "openshift/enable-user-workload-monitoring",
            "openshift/deploy-eck-using-the-operator",
            "openshift/collect-container-logs-with-filebeat",
            "openshift/create-data-pipeline-with-logstash",
          ],
        },
        {
          type: "category",
          label: "Miscellaneous",
          link: {
            type: "generated-index",
            title: "Miscellaneous",
            description: "Articles on miscellaneous topics",
          },
          items: [
            "openshift/oc-completion-bash",
            "openshift/failedmount-due-to-multipathd-not-running",
            "openshift/failedmount-due-to-exit-status-32",
            "openshift/oc-debug-node",
            "openshift/inject-trusted-cabundle-to-configmap",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Rancher",
      link: {
        type: "generated-index",
        title: "Rancher",
        description:
          "Articles related to Rancher and related SUSE enterprise K8s offerings",
      },
      items: [
        {
          type: "category",
          label: "Rancher OSS",
          link: {
            type: "generated-index",
            title: "Rancher OSS",
            description:
              "Articles related to the open source Rancher K8s management platform",
          },
          items: [
            "rancher/rancher-dev-docker",
            "rancher/rancher-keycloak-oidc",
            "rancher/rancher-custom-k3s",
            "rancher/rancher-helm-third-party",
            "rancher/rancher-import-custom-yaml",
            "rancher/rancher-k3s-cis-hardening",
          ],
        },
        {
          type: "category",
          label: "Rancher Monitoring",
          link: {
            type: "generated-index",
            title: "Rancher Monitoring",
            description: "Articles related to Rancher Monitoring",
          },
          items: [
            "rancher/rancher-monitoring-installation",
            "rancher/rancher-monitoring-receiver",
            "rancher/rancher-monitoring-persistent-dashboard",
          ],
        },
        {
          type: "category",
          label: "Rancher CIS Benchmark",
          link: {
            type: "generated-index",
            title: "Rancher CIS Benchmark",
            description: "Articles related to Rancher CIS Benchmark",
          },
          items: [
            "rancher/rancher-cis-benchmark",
            "rancher/rancher-cis-scan-alerts",
            "rancher/rancher-cis-kasten-dr-restore-broken",
          ],
        },
        {
          type: "category",
          label: "Rancher Backups",
          link: {
            type: "generated-index",
            title: "Rancher Backups",
            description: "Articles related to Rancher Backups",
          },
          items: [
            "rancher/rancher-backups-installation",
            "rancher/rancher-backups-backup-s3",
            "rancher/rancher-backups-migration-missing-job",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "DaoCloud",
      link: {
        type: "generated-index",
        title: "DaoCloud",
        description: "Articles related to DaoCloud",
      },
      items: [
        {
          type: "category",
          label: "DCE5 Installation",
          link: {
            type: "generated-index",
            title: "DCE5 Installation",
            description: "Articles related to DCE5 installation",
          },
          items: [
            "daocloud/install-dce5-community",
            "daocloud/dce5-community-modules",
          ],
        },
        {
          type: "category",
          label: "Container Management (Kpanda)",
          link: {
            type: "generated-index",
            title: "Container Management (Kpanda)",
            description: "Articles related to container management (Kpanda)",
          },
          items: [
            "daocloud/kpanda-integrate-cluster",
            "daocloud/kpanda-helm-auto-update",
            "daocloud/kpanda-install-hwameistor",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "On-Premises Infra",
      link: {
        type: "generated-index",
        title: "On-Premises Infra",
        description: "Articles related to on-premises infrastructure",
      },
      items: [
        {
          type: "category",
          label: "Linux",
          link: {
            type: "generated-index",
            title: "Linux",
            description: "Articles related to Linux",
          },
          items: [
            "on-prem/set-up-apache-with-vhost-on-rhel-9",
            "on-prem/legacy-app-podman-kube-rhel-9",
            "on-prem/ubuntu-jammy-bind9",
            "on-prem/check-tcp-udp-port-open-minimal-linux",
            "on-prem/openssl-cheatsheet",
            "on-prem/ssh-password-auth-not-enabled-even-when-set-to-yes",
            "on-prem/centos-9-stream-unlock-account-reset-password",
            "on-prem/apache-httpd-mtls",
            "on-prem/curl-mtls",
            "on-prem/cloud-init-example",
          ],
        },
        {
          type: "category",
          label: "Networking",
          link: {
            type: "generated-index",
            title: "Networking",
            description: "Articles related to networking",
          },
          items: [
            "on-prem/cisco-switch-ssh-pubkey-authentication",
            "on-prem/fortigate-ipsec-vpn-ubuntu",
            "on-prem/h3c-switch-read-electronic-label-info",
          ],
        },
        {
          type: "category",
          label: "VMware",
          link: {
            type: "generated-index",
            title: "VMware",
            description: "Articles related to VMware",
          },
          items: ["on-prem/vmware-datastore-upload-file-python"],
        },
        {
          type: "category",
          label: "Commvault",
          link: {
            type: "generated-index",
            title: "Commvault",
            description: "Articles related to Commvault",
          },
          items: [
            "on-prem/commvault-custom-package-silent-install-windows",
            "on-prem/commvault-register-unix-file-server-client-cli",
            "on-prem/commvault-agent-create-systemd-services-manually",
            "on-prem/commvault-convert-ma-to-frel",
          ],
        },
        {
          type: "category",
          label: "Windows",
          link: {
            type: "generated-index",
            title: "Windows",
            description: "Articles related to Windows",
          },
          items: [
            "on-prem/enable-telnet-client-on-windows",
            "on-prem/enable-openssh-server-on-windows",
            "on-prem/create-replicated-ad-domain-powershell",
            "on-prem/allow-domain-users-to-log-in-via-rdp",
            "on-prem/change-dns-hostname-of-ad-ds-domain-controller",
            "on-prem/windows-pwsh-send-mailmessage-starttls",
            "on-prem/windows-mtls-client-certificate-key-pair",
            "on-prem/adds-enable-ldaps",
          ],
        },
        {
          type: "category",
          label: "Keycloak",
          link: {
            type: "generated-index",
            title: "Keycloak",
            description: "Articles related to Keycloak",
          },
          items: [
            "on-prem/keycloak-oss-openjdk",
            "on-prem/keycloak-ad-ds-user-federation",
            "on-prem/keycloak-realm-enforce-mfa",
            "on-prem/keycloak-ldap-sync-groups",
            "rancher/rancher-keycloak-oidc",
            "kubernetes/keycloak-oauth2-proxy-ingress-nginx",
            "veeam/kasten-k10-mc-keycloak-oidc",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Veeam",
      link: {
        type: "generated-index",
        title: "Veeam",
        description: "Articles related to Veeam",
      },
      items: [
        {
          type: "category",
          label: "Kasten K10",
          link: {
            type: "generated-index",
            title: "Kasten K10",
            description: "Articles related to Kasten K10",
          },
          items: [
            "veeam/kasten-k10-installation",
            "veeam/delete-k10-manual-backups",
            "veeam/kasten-k10-gateway-pod-crashloopbackoff",
            "veeam/kasten-k10-dr-job-failed-to-start-kopia-api-server",
            "veeam/kasten-k10-transform-set-cross-site-app-recovery",
            "veeam/kasten-k10-multi-cluster",
            "veeam/kasten-k10-mc-keycloak-oidc",
            "rancher/rancher-monitoring-persistent-dashboard",
            "veeam/kasten-k10-policy-filters",
            "rancher/rancher-cis-kasten-dr-restore-broken",
          ],
        },
        {
          type: "category",
          label: "VBR",
          link: {
            type: "generated-index",
            title: "VBR",
            description: "Articles related to Veeam Backup & Replication (VBR)",
          },
          items: [
            "veeam/vbr-ubuntu-linux-hardened-repository",
            "veeam/vbr-centos-linux-hardened-repository",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "NetApp",
      link: {
        type: "generated-index",
        title: "NetApp",
        description: "Articles related to NetApp",
      },
      items: [
        {
          type: "category",
          label: "ONTAP 9.x",
          link: {
            type: "generated-index",
            title: "ONTAP 9.x",
            description: "Articles related to ONTAP 9.x",
          },
          items: [
            "netapp/ontap-9-quickstart-concepts",
            "netapp/ontap-9-quickstart-cmdline",
            "netapp/assign-disk-to-node",
            "netapp/create-svm-and-enable-vsadmin-ssh-login",
            "netapp/activate-ontap-features-with-licenses",
            "netapp/prepare-svm-as-trident-san-backend",
            "netapp/prepare-svm-as-trident-nas-backend",
          ],
        },
        {
          type: "category",
          label: "Astra Trident",
          link: {
            type: "generated-index",
            title: "Astra Trident",
            description: "Articles related to Astra Trident",
          },
          items: [
            "netapp/install-trident-using-the-operator",
            "netapp/create-tbc-for-san",
            "netapp/tridentctl-completion-bash",
            "netapp/create-tbc-for-nas",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "AI/ML",
      link: {
        type: "generated-index",
        title: "AI/ML",
        description: "Articles related to AI/ML",
      },
      items: [
        "aiml/install-pyenv",
        "aiml/coral-usb-accelerator",
        "aiml/tensorflow-install-timeout",
        "aiml/keras3-coral-usb-accelerator",
      ],
    },
    {
      type: "category",
      label: "Proxmox",
      link: {
        type: "generated-index",
        title: "Proxmox",
        description: "Articles related to Proxmox",
      },
      items: [
        {
          type: "category",
          label: "Virtual Environment",
          link: {
            type: "generated-index",
            title: "Virtual Environment",
            description: "Articles related to Proxmox Virtual Environment (VE)",
          },
          items: [
            "proxmox/proxmox-ve-8p2-installation",
            "proxmox/proxmox-ve-cluster",
            "proxmox/proxmox-ve-vlan-for-guest-networks",
            "proxmox/proxmox-ve-configure-lvm-as-shared-storage-from-iscsi-luns",
            "proxmox/proxmox-ve-win22-server",
            "proxmox/proxmox-ve-ldap-auth",
            "proxmox/proxmox-ve-storage-live-migration",
            "proxmox/proxmox-ve-vm-live-migration-dedicated-network",
            "proxmox/proxmox-ve-ct",
            "proxmox/proxmox-ve-ubuntu-server",
            "proxmox/proxmox-ve-update-repositories",
            "proxmox/proxmox-ve-new-pbs",
            "proxmox/proxmox-ve-qdevice",
            "proxmox/proxmox-ve-zfs",
            "proxmox/proxmox-ve-from-vmware",
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
