name: GitHub Actions pipeline for Technical KB
on:
  push:
    branches:
      - main
jobs:
  technical-kb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Node.js 22 LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint articles
        run: |
          npx markdownlint-cli2 "blog/**/*.md" "docs/**/*.md"
      - name: Lint code
        run: |
          npx prettier . --check
      - name: Build Docusaurus
        run: |
          npm ci --omit=dev --ignore-scripts
          npm run build
